//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO_ORDERS
    {
        public decimal ORDER_ID { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public Nullable<decimal> ORDER_TOTAL { get; set; }
        public Nullable<System.DateTime> ORDER_TIMESTAMP { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
    }
}
