//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO_USUARIO
    {
        public decimal ID_DOCUMENTO_USUARIO { get; set; }
        public Nullable<decimal> ID_DOCUMENTO { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    }
}
