//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        public decimal ID_DOCUMENTO { get; set; }
        public string NOMBRE_DOCUMENTO { get; set; }
        public string GUID { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    }
}
