//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.ROL_USUARIO = new HashSet<ROL_USUARIO>();
        }
    
        public decimal ID_EMPLEADO { get; set; }
        public string SNOMBRE_EMPLEADO { get; set; }
        public string PAPELLIDO_EMPLEADO { get; set; }
        public string SAPELLIDO_EMPLEADO { get; set; }
        public decimal EDAD_EMPLEADO { get; set; }
        public decimal RUN_EMPLEADO { get; set; }
        public string DV_EMPLEADO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> ID_COMUNA { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
        public Nullable<decimal> ID_AREA { get; set; }
        public Nullable<decimal> ID_CARGO { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROL_USUARIO> ROL_USUARIO { get; set; }
    }
}
